# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pattern.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pattern(object):
    def setupUi(self, Pattern):
        Pattern.setObjectName("Pattern")
        Pattern.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(Pattern)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.polarplot = QtWidgets.QWidget(Pattern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polarplot.sizePolicy().hasHeightForWidth())
        self.polarplot.setSizePolicy(sizePolicy)
        self.polarplot.setObjectName("polarplot")
        self.gridLayout_3.addWidget(self.polarplot, 0, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Pattern)
        QtCore.QMetaObject.connectSlotsByName(Pattern)

    def retranslateUi(self, Pattern):
        _translate = QtCore.QCoreApplication.translate
        Pattern.setWindowTitle(_translate("Pattern", "Antenna pattern"))
