# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pattern.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pattern(object):
    def setupUi(self, Pattern):
        Pattern.setObjectName("Pattern")
        Pattern.resize(600, 600)
        self.gridLayout = QtWidgets.QGridLayout(Pattern)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(Pattern)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 3, 1, 1)
        self.refdBm = QtWidgets.QSpinBox(Pattern)
        self.refdBm.setMinimum(-145)
        self.refdBm.setMaximum(-25)
        self.refdBm.setProperty("value", -73)
        self.refdBm.setObjectName("refdBm")
        self.gridLayout_3.addWidget(self.refdBm, 1, 6, 1, 1)
        self.rotateTime = QtWidgets.QSpinBox(Pattern)
        self.rotateTime.setMinimum(1)
        self.rotateTime.setMaximum(360)
        self.rotateTime.setProperty("value", 72)
        self.rotateTime.setObjectName("rotateTime")
        self.gridLayout_3.addWidget(self.rotateTime, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(Pattern)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 5, 1, 1)
        self.plotwidget = PlotWidget(Pattern)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget.sizePolicy().hasHeightForWidth())
        self.plotwidget.setSizePolicy(sizePolicy)
        self.plotwidget.setObjectName("plotwidget")
        self.gridLayout_3.addWidget(self.plotwidget, 0, 0, 1, 9)
        self.rotating = QtWidgets.QPushButton(Pattern)
        self.rotating.setCheckable(False)
        self.rotating.setObjectName("rotating")
        self.gridLayout_3.addWidget(self.rotating, 1, 0, 1, 1)
        self.clockwise = QtWidgets.QCheckBox(Pattern)
        self.clockwise.setChecked(True)
        self.clockwise.setObjectName("clockwise")
        self.gridLayout_3.addWidget(self.clockwise, 1, 1, 1, 1)
        self.heading = QtWidgets.QSpinBox(Pattern)
        self.heading.setMaximum(360)
        self.heading.setSingleStep(1)
        self.heading.setObjectName("heading")
        self.gridLayout_3.addWidget(self.heading, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Pattern)
        QtCore.QMetaObject.connectSlotsByName(Pattern)

    def retranslateUi(self, Pattern):
        _translate = QtCore.QCoreApplication.translate
        Pattern.setWindowTitle(_translate("Pattern", "Antenna pattern"))
        self.label.setText(_translate("Pattern", "Rotate time"))
        self.refdBm.setToolTip(_translate("Pattern", "Approx signal strength when pointing directly at source"))
        self.refdBm.setSuffix(_translate("Pattern", " dBm"))
        self.rotateTime.setSuffix(_translate("Pattern", " s"))
        self.label_6.setText(_translate("Pattern", "Test signal"))
        self.rotating.setToolTip(_translate("Pattern", "Click when rotating starts"))
        self.rotating.setText(_translate("Pattern", "Start"))
        self.clockwise.setText(_translate("Pattern", "Clockwise"))
        self.heading.setSuffix(_translate("Pattern", " deg"))
from pyqtgraph import PlotWidget
