# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fading.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fading(object):
    def setupUi(self, fading):
        fading.setObjectName("fading")
        fading.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(fading)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grView = GraphicsView(fading)
        self.grView.setObjectName("grView")
        self.gridLayout_3.addWidget(self.grView, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(fading)
        QtCore.QMetaObject.connectSlotsByName(fading)

    def retranslateUi(self, fading):
        _translate = QtCore.QCoreApplication.translate
        fading.setWindowTitle(_translate("fading", "Signal level over Time"))
from pyqtgraph import GraphicsView
