# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filebrowse.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filebrowse(object):
    def setupUi(self, Filebrowse):
        Filebrowse.setObjectName("Filebrowse")
        Filebrowse.resize(800, 400)
        self.listWidget = QtWidgets.QListWidget(Filebrowse)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 301, 311))
        self.listWidget.setObjectName("listWidget")
        self.download = QtWidgets.QPushButton(Filebrowse)
        self.download.setGeometry(QtCore.QRect(10, 350, 80, 26))
        self.download.setObjectName("download")
        self.picture = QtWidgets.QLabel(Filebrowse)
        self.picture.setGeometry(QtCore.QRect(320, 20, 471, 321))
        self.picture.setText("")
        self.picture.setScaledContents(False)
        self.picture.setObjectName("picture")
        self.downloadInfo = QtWidgets.QLabel(Filebrowse)
        self.downloadInfo.setGeometry(QtCore.QRect(10, 380, 791, 20))
        self.downloadInfo.setText("")
        self.downloadInfo.setObjectName("downloadInfo")

        self.retranslateUi(Filebrowse)
        QtCore.QMetaObject.connectSlotsByName(Filebrowse)

    def retranslateUi(self, Filebrowse):
        _translate = QtCore.QCoreApplication.translate
        Filebrowse.setWindowTitle(_translate("Filebrowse", "File List"))
        self.download.setText(_translate("Filebrowse", "Save"))
