# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phasenoise.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Phasenoise(object):
    def setupUi(self, Phasenoise):
        Phasenoise.setObjectName("Phasenoise")
        Phasenoise.resize(857, 528)
        self.layoutWidget = QtWidgets.QWidget(Phasenoise)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 811, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.noiseWidget = PlotWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseWidget.sizePolicy().hasHeightForWidth())
        self.noiseWidget.setSizePolicy(sizePolicy)
        self.noiseWidget.setObjectName("noiseWidget")
        self.gridLayout_3.addWidget(self.noiseWidget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.centre = QtWidgets.QPushButton(self.layoutWidget)
        self.centre.setObjectName("centre")
        self.gridLayout_3.addWidget(self.centre, 1, 1, 1, 1)

        self.retranslateUi(Phasenoise)
        QtCore.QMetaObject.connectSlotsByName(Phasenoise)

    def retranslateUi(self, Phasenoise):
        _translate = QtCore.QCoreApplication.translate
        Phasenoise.setWindowTitle(_translate("Phasenoise", "Phase Noise"))
        self.centre.setText(_translate("Phasenoise", "Centre"))
from pyqtgraph import PlotWidget
