# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filebrowse.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filebrowse(object):
    def setupUi(self, Filebrowse):
        Filebrowse.setObjectName("Filebrowse")
        Filebrowse.resize(800, 600)
        self.gridLayout_3 = QtWidgets.QGridLayout(Filebrowse)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.listWidget = QtWidgets.QListWidget(Filebrowse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.listWidget)
        self.picture = QtWidgets.QLabel(Filebrowse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture.sizePolicy().hasHeightForWidth())
        self.picture.setSizePolicy(sizePolicy)
        self.picture.setMinimumSize(QtCore.QSize(480, 320))
        self.picture.setText("")
        self.picture.setScaledContents(False)
        self.picture.setObjectName("picture")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.picture)
        self.download = QtWidgets.QPushButton(Filebrowse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.download.sizePolicy().hasHeightForWidth())
        self.download.setSizePolicy(sizePolicy)
        self.download.setMinimumSize(QtCore.QSize(95, 0))
        self.download.setObjectName("download")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.download)
        self.downloadInfo = QtWidgets.QLabel(Filebrowse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadInfo.sizePolicy().hasHeightForWidth())
        self.downloadInfo.setSizePolicy(sizePolicy)
        self.downloadInfo.setText("")
        self.downloadInfo.setObjectName("downloadInfo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.downloadInfo)
        self.saveAll = QtWidgets.QPushButton(Filebrowse)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAll.sizePolicy().hasHeightForWidth())
        self.saveAll.setSizePolicy(sizePolicy)
        self.saveAll.setMinimumSize(QtCore.QSize(95, 0))
        self.saveAll.setObjectName("saveAll")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.saveAll)
        self.askForPath = QtWidgets.QCheckBox(Filebrowse)
        self.askForPath.setChecked(False)
        self.askForPath.setObjectName("askForPath")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.askForPath)
        self.saveProgress = QtWidgets.QProgressBar(Filebrowse)
        self.saveProgress.setProperty("value", 0)
        self.saveProgress.setObjectName("saveProgress")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.saveProgress)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(Filebrowse)
        QtCore.QMetaObject.connectSlotsByName(Filebrowse)

    def retranslateUi(self, Filebrowse):
        _translate = QtCore.QCoreApplication.translate
        Filebrowse.setWindowTitle(_translate("Filebrowse", "File List"))
        self.download.setText(_translate("Filebrowse", "Save selected"))
        self.saveAll.setText(_translate("Filebrowse", "Save all files"))
        self.askForPath.setText(_translate("Filebrowse", "Ask for folder location for each file"))
