# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phasenoise.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Phasenoise(object):
    def setupUi(self, Phasenoise):
        Phasenoise.setObjectName("Phasenoise")
        Phasenoise.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(Phasenoise)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 3, 1, 1)
        self.plotWidget = PlotWidget(Phasenoise)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotWidget.sizePolicy().hasHeightForWidth())
        self.plotWidget.setSizePolicy(sizePolicy)
        self.plotWidget.setObjectName("plotWidget")
        self.gridLayout_3.addWidget(self.plotWidget, 0, 0, 1, 4)
        self.centre = QtWidgets.QPushButton(Phasenoise)
        self.centre.setObjectName("centre")
        self.gridLayout_3.addWidget(self.centre, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Phasenoise)
        QtCore.QMetaObject.connectSlotsByName(Phasenoise)

    def retranslateUi(self, Phasenoise):
        _translate = QtCore.QCoreApplication.translate
        Phasenoise.setWindowTitle(_translate("Phasenoise", "Phase Noise"))
        self.centre.setText(_translate("Phasenoise", "Centre"))
from pyqtgraph import PlotWidget
