name: macOS x86-64 Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'macOS 13 on x86-64'

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r src/requirements.txt

      - name: Build with PyInstaller
        run: |
          cd src
          pyinstaller QtTinySA.spec
          cd ..

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtTinySA_mac_x86-64
          path: ~/work/QtTinySA/QtTinySA/src/dist

