name: Ubuntu Linux Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'ubuntu latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.12.0
          pip install -r src/requirements.txt

      - name: Build with PyInstaller
        run: |
          cd src
          pyinstaller QtTinySA.spec
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtTinySA.bin
          path: ~/work/QtTinySA/QtTinySA/src/dist
